[package]
name = "app"
version = "0.1.0"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"


[build-dependencies]
swift-rs = { version = "0.3", features = ["build"] }

[dependencies]
swift-rs = "0.3"
